---
- name: Install Rethinkdb
  hosts: target-vm
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

  roles:
    - dependencies
    - install
    - config
    - launch